FROM golang:1.12.9 as build-backend
WORKDIR /go/src/github.com/reportportal/service-ui/
ARG service
ARG version
ENV GO111MODULE=on
COPY ./Makefile ./go.mod .golangci.yml ./
RUN make get-build-deps

COPY ./main.go ./
RUN make fmt
RUN make build-server v=$version

FROM node:11-alpine as build-frontend
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY ./app/ /usr/src/app/
RUN npm ci
RUN NODE_OPTIONS=--max_old_space_size=4096 npm run build && npm run test

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=build-backend /go/src/github.com/reportportal/service-ui/bin/service-ui /
COPY --from=build-frontend /usr/src/app/build /public

ENV RP_STATICS_PATH=/public

EXPOSE 8080
ENTRYPOINT ["/service-ui"]