/*
 * Copyright 2026 EPAM Systems
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { shallow } from 'enzyme';

import { AiChip } from 'pages/inside/aiFactory/common';
import { ReviewFlags } from 'pages/inside/aiFactory/library';

import { TestCaseNameCell } from './testCaseNameCell';

jest.mock('react-intl', () => ({
  defineMessages: (messages: unknown) => messages,
  useIntl: () => ({
    formatMessage: (message: { defaultMessage: string }, values?: { number?: number }) =>
      message.defaultMessage.replace('{number}', String(values?.number)),
  }),
}));
jest.mock('common/utils', () => ({
  createClassnames: () => (...classNames: string[]) => classNames.filter(Boolean).join(' '),
  highlightText: (text: string) => text,
}));
jest.mock('pages/inside/productVersionPage/linkedTestCasesTab/tagList', () => ({
  AdaptiveTagList: 'AdaptiveTagList',
}));
jest.mock('pages/inside/common/priorityIcon', () => ({ PriorityIcon: 'PriorityIcon' }));
jest.mock('pages/inside/aiFactory/library', () => ({ ReviewFlags: 'ReviewFlags' }));
jest.mock('components/main/conditionalTooltip', () => ({
  ConditionalTooltip: 'ConditionalTooltip',
}));

const baseProps = {
  displayId: 'TC42',
  priority: 'medium' as const,
  name: 'Generated case',
  tags: ['smoke'],
};
const ai = {
  generatedByIteration: { pipelineId: 17, iterationId: 103, number: 4 },
  modifiedByAgent: false,
  factoryKey: 'spec::case',
};

describe('TestCaseNameCell AI metadata', () => {
  test('shows the originating iteration in the AI chip tooltip', () => {
    const wrapper = shallow(<TestCaseNameCell {...baseProps} ai={ai} />);

    expect(wrapper.find(AiChip).prop('tooltip')).toBe('Generated by Iteration #4');
  });

  test('mentions agent modification in the AI chip tooltip', () => {
    const wrapper = shallow(
      <TestCaseNameCell {...baseProps} ai={{ ...ai, modifiedByAgent: true }} />,
    );

    expect(wrapper.find(AiChip).prop('tooltip')).toBe(
      'Generated by Iteration #4 · modified by agent',
    );
  });

  test('passes review flags through for an AI-generated row', () => {
    const review = { unsentCommentsCount: 2 };
    const wrapper = shallow(<TestCaseNameCell {...baseProps} ai={ai} review={review} />);

    expect(wrapper.find(ReviewFlags).prop('review')).toBe(review);
  });

  test('does not show AI metadata for a manual row', () => {
    const wrapper = shallow(
      <TestCaseNameCell {...baseProps} review={{ unsentCommentsCount: 2 }} />,
    );

    expect(wrapper.find(AiChip)).toHaveLength(0);
    expect(wrapper.find(ReviewFlags)).toHaveLength(0);
  });

  test('uses a non-interactive AI tooltip trigger', () => {
    const nameCell = shallow(<TestCaseNameCell {...baseProps} ai={ai} />);
    const chipWrapper = nameCell.find('div.ai-chip');
    const aiChip = shallow(<AiChip tooltip="Generated by Iteration #4" />);
    const trigger = aiChip.find('span[data-automation-id="aiChip"]');

    expect(chipWrapper).toHaveLength(1);
    expect(chipWrapper.find(AiChip)).toHaveLength(1);
    expect(chipWrapper.find('button')).toHaveLength(0);
    expect(trigger).toHaveLength(1);
    expect(trigger.prop('role')).toBeUndefined();
    expect(trigger.prop('tabIndex')).toBeUndefined();
    expect(trigger.prop('onClick')).toBeUndefined();
    ['button', 'a', 'input', 'select', 'textarea'].forEach((selector) => {
      expect(trigger.find(selector)).toHaveLength(0);
    });
  });
});
