export const START_LAUNCH = 'startLaunch';
export const FINISH_LAUNCH = 'finishLaunch';
export const DELETE_LAUNCH = 'deleteLaunch';
export const POST_ISSUE = 'postIssue';
export const LINK_ISSUE = 'linkIssue';
export const UNLINK_ISSUE = 'unlinkIssue';
export const CREATE_USER = 'createUser';
export const CREATE_DASHBOARD = 'createDashboard';
export const UPDATE_DASHBOARD = 'updateDashboard';
export const DELETE_DASHBOARD = 'deleteDashboard';
export const CREATE_WIDGET = 'createWidget';
export const UPDATE_WIDGET = 'updateWidget';
export const DELETE_WIDGET = 'deleteWidget';
export const CREATE_FILTER = 'createFilter';
export const UPDATE_FILTER = 'updateFilter';
export const DELETE_FILTER = 'deleteFilter';
export const CREATE_BTS = 'createBts';
export const UPDATE_BTS = 'updateBts';
export const DELETE_BTS = 'deleteBts';
export const UPDATE_PROJECT = 'updateProject';
export const UPDATE_ANALYZER = 'updateAnalyzer';
export const GENERATE_INDEX = 'generateIndex';
export const DELETE_INDEX = 'deleteIndex';
export const CREATE_DEFECT = 'createDefect';
export const UPDATE_DEFECT = 'updateDefect';
export const DELETE_DEFECT = 'deleteDefect';
export const START_IMPORT = 'startImport';
export const FINISH_IMPORT = 'finishImport';
export const UPDATE_NOTIFICATIONS = 'updateEmail';
export const SWITCH_ON_NOTIFICATIONS = 'onEmail';
export const SWITCH_OFF_NOTIFICATIONS = 'offEmail';
export const UPDATE_ITEM = 'updateItem';

// grouped actions
export const ACTIONS_WITH_ISSUES = 'issuesActions';
export const ACTIONS_WITH_DASHBOARDS = 'dashboardsActions';
export const ACTIONS_WITH_WIDGETS = 'widgetsActions';
export const ACTIONS_WITH_FILTERS = 'filtersActions';
export const ACTIONS_WITH_BTS = 'btsActions';
export const ACTIONS_WITH_AA_SETTINGS = 'aaSettingsActions';
export const ACTIONS_WITH_DEFECTS = 'defectsActions';
export const ACTIONS_WITH_IMPORT = 'importActions';
export const ACTIONS_WITH_NOTIFICATIONS = 'notificationsActions';
export const ACTIONS_WITH_LAUNCH = 'launchActions';

export const GROUP_TO_ACTION_MAP = {
  [ACTIONS_WITH_ISSUES]: [POST_ISSUE, LINK_ISSUE, UNLINK_ISSUE],
  [ACTIONS_WITH_DASHBOARDS]: [CREATE_DASHBOARD, UPDATE_DASHBOARD, DELETE_DASHBOARD],
  [ACTIONS_WITH_WIDGETS]: [CREATE_WIDGET, UPDATE_WIDGET, DELETE_WIDGET],
  [ACTIONS_WITH_FILTERS]: [CREATE_FILTER, UPDATE_FILTER, DELETE_FILTER],
  [ACTIONS_WITH_BTS]: [CREATE_BTS, UPDATE_BTS, DELETE_BTS],
  [ACTIONS_WITH_AA_SETTINGS]: [UPDATE_ANALYZER, GENERATE_INDEX, DELETE_INDEX],
  [ACTIONS_WITH_DEFECTS]: [UPDATE_DEFECT, DELETE_DEFECT],
  [ACTIONS_WITH_IMPORT]: [START_IMPORT, FINISH_IMPORT],
  [ACTIONS_WITH_NOTIFICATIONS]: [
    UPDATE_NOTIFICATIONS,
    SWITCH_ON_NOTIFICATIONS,
    SWITCH_OFF_NOTIFICATIONS,
  ],
};

export const ACTION_TO_GROUP_MAP = {
  [POST_ISSUE]: ACTIONS_WITH_ISSUES,
  [LINK_ISSUE]: ACTIONS_WITH_ISSUES,
  [UNLINK_ISSUE]: ACTIONS_WITH_ISSUES,

  [CREATE_DASHBOARD]: ACTIONS_WITH_DASHBOARDS,
  [UPDATE_DASHBOARD]: ACTIONS_WITH_DASHBOARDS,
  [DELETE_DASHBOARD]: ACTIONS_WITH_DASHBOARDS,

  [CREATE_WIDGET]: ACTIONS_WITH_WIDGETS,
  [UPDATE_WIDGET]: ACTIONS_WITH_WIDGETS,
  [DELETE_WIDGET]: ACTIONS_WITH_WIDGETS,

  [CREATE_FILTER]: ACTIONS_WITH_FILTERS,
  [UPDATE_FILTER]: ACTIONS_WITH_FILTERS,
  [DELETE_FILTER]: ACTIONS_WITH_FILTERS,

  [CREATE_BTS]: ACTIONS_WITH_BTS,
  [UPDATE_BTS]: ACTIONS_WITH_BTS,
  [DELETE_BTS]: ACTIONS_WITH_BTS,

  [UPDATE_ANALYZER]: ACTIONS_WITH_AA_SETTINGS,
  [GENERATE_INDEX]: ACTIONS_WITH_AA_SETTINGS,
  [DELETE_INDEX]: ACTIONS_WITH_AA_SETTINGS,

  [UPDATE_DEFECT]: ACTIONS_WITH_DEFECTS,
  [DELETE_DEFECT]: ACTIONS_WITH_DEFECTS,

  [START_IMPORT]: ACTIONS_WITH_IMPORT,
  [FINISH_IMPORT]: ACTIONS_WITH_IMPORT,

  [UPDATE_NOTIFICATIONS]: ACTIONS_WITH_NOTIFICATIONS,
  [SWITCH_ON_NOTIFICATIONS]: ACTIONS_WITH_NOTIFICATIONS,
  [SWITCH_OFF_NOTIFICATIONS]: ACTIONS_WITH_NOTIFICATIONS,
};
