import {
  BTS_GROUP_TYPE,
  NOTIFICATION_GROUP_TYPE,
  AUTHORIZATION_GROUP_TYPE,
  OTHER_GROUP_TYPE,
} from './pluginsGroupTypes';

export const JIRA = 'jira';
export const RALLY = 'rally';
export const EMAIL = 'email';
export const SAUCE_LABS = 'saucelabs';
export const SAML = 'saml';

export const INTEGRATION_NAMES_BY_GROUP_TYPES_MAP = {
  [BTS_GROUP_TYPE]: [JIRA, RALLY],
  [NOTIFICATION_GROUP_TYPE]: [EMAIL],
  [OTHER_GROUP_TYPE]: [SAUCE_LABS],
  [AUTHORIZATION_GROUP_TYPE]: [SAML],
};

export const GROUP_TYPES_BY_INTEGRATION_NAMES_MAP = {
  [JIRA]: BTS_GROUP_TYPE,
  [RALLY]: BTS_GROUP_TYPE,
  [EMAIL]: NOTIFICATION_GROUP_TYPE,
  [SAML]: AUTHORIZATION_GROUP_TYPE,
  [SAUCE_LABS]: OTHER_GROUP_TYPE,
};
