export const LAUNCH_ANALYZE_TYPES = {
  ANALYZER_MODE: {
    ALL: 'ALL',
    LAUNCH_NAME: 'LAUNCH_NAME',
    CURRENT_LAUNCH: 'CURRENT_LAUNCH',
  },
  ANALYZE_ITEMS_MODE: {
    TO_INVESTIGATE: 'TO_INVESTIGATE',
    AUTO_ANALYZED: 'AUTO_ANALYZED',
    MANUALLY_ANALYZED: 'MANUALLY_ANALYZED',
  },
};
