/*
 * Copyright 2019 EPAM Systems
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { MEMBER, MANAGER, VIEWER, EDITOR } from 'common/constants/projectRoles';
import { PermissionsMap } from 'types/roles';

export const ALL = 'ALL';
export const OWNER = 'OWNER';

export const ACTIONS: Record<string, string> = {
  ACCESS_TO_MANAGEMENT_SYSTEM: 'ACCESS_TO_MANAGEMENT_SYSTEM',
  // PROJECT
  CHANGE_ACCESS_PROJECT: 'CHANGE_ACCESS_PROJECT',
  CREATE_PROJECT: 'CREATE_PROJECT',
  DELETE_PROJECT: 'DELETE_PROJECT',
  RENAME_PROJECT: 'RENAME_PROJECT',
  INVITE_USER_TO_PROJECT: 'INVITE_USER_TO_PROJECT',

  // ORGANIZATION
  INVITE_USER_TO_ORGANIZATION: 'INVITE_USER_TO_ORGANIZATION',
  CREATE_ORGANIZATION: 'CREATE_ORGANIZATION',
  DELETE_ORGANIZATION: 'DELETE_ORGANIZATION',
  RENAME_ORGANIZATION: 'RENAME_ORGANIZATION',
  SEE_ORGANIZATION_MEMBERS: 'SEE_ORGANIZATION_MEMBERS',
  UPDATE_ORGANIZATION_SETTINGS: 'UPDATE_ORGANIZATION_SETTINGS',
  WORK_WITH_ORGANIZATIONS_SORTING: 'WORK_WITH_ORGANIZATIONS_SORTING',
  EXPORT_ORGANIZATIONS: 'EXPORT_ORGANIZATIONS',

  // SETTINGS
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',
  SEE_SETTINGS: 'SEE_SETTINGS',

  // USERS_MANAGEMENT
  MANAGE_USERS: 'MANAGE_USERS',
  ASSIGN_UNASSIGN_INTERNAL_USER: 'ASSIGN_UNASSIGN_INTERNAL_USER',
  CHANGE_USER_ROLE: 'CHANGE_USER_ROLE',
  DELETE_USER: 'DELETE_USER',

  // LAUNCHES
  EDIT_LAUNCH: 'EDIT_LAUNCH',

  BULK_EDIT_ITEMS: 'BULK_EDIT_ITEMS', // for what? launche?
  MAKE_DECISION: 'MAKE_DECISION',
  DELETE_TEST_ITEM: 'DELETE_TEST_ITEM',
  CHANGE_TEST_ITEM_STATUS: 'CHANGE_TEST_ITEM_STATUS',
  MANAGE_BTS_ISSUES: 'MANAGE_BTS_ISSUES',
  WORK_WITH_FILTERS: 'WORK_WITH_FILTERS',
  WORK_WITH_ORGANIZATION_FILTER: 'WORK_WITH_ORGANIZATION_FILTER',
  READ_DATA: 'READ_DATA',
  RESIZE_AND_DRAG_WIDGETS: 'RESIZE_AND_DRAG_WIDGETS',
  SEE_DEMO_DATA: 'SEE_DEMO_DATA',
  WORK_WITH_DEFECT_TYPES: 'WORK_WITH_DEFECT_TYPES',
  WORK_WITH_WIDGETS: 'WORK_WITH_WIDGETS',
  REPORT_LAUNCHES: 'REPORT_LAUNCHES',
  WORK_WITH_DASHBOARD: 'WORK_WITH_DASHBOARD',
  WORK_WITH_TESTS: 'WORK_WITH_TESTS',
  SEE_EMAIL_MEMBERS: 'SEE_EMAIL_MEMBERS',
  SEE_ROW_ACTION_MENU: 'SEE_ROW_ACTION_MENU',
  ACCESS_INSTANCE_LEVEL_PAGES: 'ACCESS_INSTANCE_LEVEL_PAGES',
  ACTIVITY_OPTION: 'ACTIVITY_OPTION',
  INSTANCE_LEVEL_PLUGIN_PAGES: 'INSTANCE_LEVEL_PLUGIN_PAGES',
  VIEW_INFO_BILLING: 'VIEW_INFO_BILLING',
  SEE_MEMBERS: 'SEE_MEMBERS',
  EDIT_OWN_ACCOUNT: 'EDIT_OWN_ACCOUNT',

  // INSTANCE
  UPDATE_USER_INSTANCE_ROLE: 'UPDATE_USER_INSTANCE_ROLE',

  // MANUAL LAUNCHES
  EDIT_MANUAL_LAUNCH: 'EDIT_MANUAL_LAUNCH',
  // TEST CASE
  EDIT_TEST_CASE: 'EDIT_TEST_CASE',
  // TEST PLAN
  EDIT_TEST_PLAN: 'EDIT_TEST_PLAN',
};

export const PERMISSIONS_MAP: PermissionsMap = {
  [MANAGER]: {
    [ACTIONS.SEE_SETTINGS]: true,
    [ACTIONS.UPDATE_SETTINGS]: true,
    [ACTIONS.MANAGE_USERS]: true,
    [ACTIONS.ASSIGN_UNASSIGN_INTERNAL_USER]: true,
    [ACTIONS.SEE_MEMBERS]: true,
    [ACTIONS.CHANGE_USER_ROLE]: true,
    [ACTIONS.REPORT_LAUNCHES]: true,
    [ACTIONS.EDIT_LAUNCH]: true,
    [ACTIONS.BULK_EDIT_ITEMS]: true,
    [ACTIONS.CHANGE_TEST_ITEM_STATUS]: true,
    [ACTIONS.DELETE_TEST_ITEM]: true,
    [ACTIONS.MAKE_DECISION]: true,
    [ACTIONS.MANAGE_BTS_ISSUES]: true,
    [ACTIONS.WORK_WITH_FILTERS]: true,
    [ACTIONS.WORK_WITH_WIDGETS]: true,
    [ACTIONS.SEE_ORGANIZATION_MEMBERS]: true,
    [ACTIONS.UPDATE_ORGANIZATION_SETTINGS]: true,
    [ACTIONS.CREATE_PROJECT]: true,
    [ACTIONS.DELETE_PROJECT]: true,
    [ACTIONS.RENAME_PROJECT]: true,
    [ACTIONS.INVITE_USER_TO_PROJECT]: true,
    [ACTIONS.INVITE_USER_TO_ORGANIZATION]: true,
    [ACTIONS.CHANGE_ACCESS_PROJECT]: true,
    [ACTIONS.VIEW_INFO_BILLING]: true,
    [ACTIONS.RENAME_ORGANIZATION]: true,
    [ACTIONS.WORK_WITH_DEFECT_TYPES]: true,
    [ACTIONS.SEE_DEMO_DATA]: true,
    [ACTIONS.WORK_WITH_DASHBOARD]: true,
    [ACTIONS.WORK_WITH_TESTS]: true,
    [ACTIONS.SEE_EMAIL_MEMBERS]: true,
    [ACTIONS.SEE_ROW_ACTION_MENU]: true,
  },
  [MEMBER]: {
    [VIEWER]: {
      [ACTIONS.SEE_SETTINGS]: false,
      [ACTIONS.SEE_MEMBERS]: false,
    },
    [EDITOR]: {
      [ACTIONS.SEE_SETTINGS]: true,
      [ACTIONS.UPDATE_SETTINGS]: true,
      [ACTIONS.MANAGE_USERS]: true,
      [ACTIONS.ASSIGN_UNASSIGN_INTERNAL_USER]: true,
      [ACTIONS.SEE_MEMBERS]: true,
      [ACTIONS.CHANGE_USER_ROLE]: true,
      [ACTIONS.REPORT_LAUNCHES]: true,
      [ACTIONS.EDIT_LAUNCH]: true,
      [ACTIONS.BULK_EDIT_ITEMS]: true,
      [ACTIONS.DELETE_TEST_ITEM]: true,
      [ACTIONS.CHANGE_TEST_ITEM_STATUS]: true,
      [ACTIONS.MAKE_DECISION]: true,
      [ACTIONS.MANAGE_BTS_ISSUES]: true,
      [ACTIONS.WORK_WITH_FILTERS]: true,
      [ACTIONS.WORK_WITH_WIDGETS]: true,
      [ACTIONS.RENAME_PROJECT]: true,
      [ACTIONS.INVITE_USER_TO_PROJECT]: true,
      [ACTIONS.WORK_WITH_DEFECT_TYPES]: true,
      [ACTIONS.SEE_DEMO_DATA]: true,
      [ACTIONS.WORK_WITH_DASHBOARD]: true,
      [ACTIONS.WORK_WITH_TESTS]: true,
      [ACTIONS.SEE_ROW_ACTION_MENU]: true,
      // MANUAL LAUNCHES
      [ACTIONS.EDIT_MANUAL_LAUNCH]: true,
      // TEST CASE
      [ACTIONS.EDIT_TEST_CASE]: true,
      // TEST PLAN
      [ACTIONS.EDIT_TEST_PLAN]: true,
    },
  },
};
