/*
 * Copyright 2019 EPAM Systems
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { MEMBER, MANAGER, VIEWER, EDITOR } from 'common/constants/projectRoles';
import { PermissionsMap } from 'types/roles';

export const ALL = 'ALL';
export const OWNER = 'OWNER';

export const ACTIONS: Record<string, string> = {
  ACCESS_TO_MANAGEMENT_SYSTEM: 'ACCESS_TO_MANAGEMENT_SYSTEM',

  // INSTANCE
  UPDATE_USER_INSTANCE_ROLE: 'UPDATE_USER_INSTANCE_ROLE',

  // LAUNCHES
  MANAGE_LAUNCHES: 'MANAGE_LAUNCHES',

  // MANUAL LAUNCHES
  MANAGE_MANUAL_LAUNCHES: 'MANAGE_MANUAL_LAUNCHES',

  // ORGANIZATION
  MANAGE_ORGANIZATIONS: 'MANAGE_ORGANIZATIONS',
  SEE_ORGANIZATION_MEMBERS: 'SEE_ORGANIZATION_MEMBERS',
  WORK_WITH_ORGANIZATION_FILTER: 'WORK_WITH_ORGANIZATION_FILTER',
  WORK_WITH_ORGANIZATIONS_SORTING: 'WORK_WITH_ORGANIZATIONS_SORTING',

  // PROJECT
  MANAGE_PROJECTS: 'MANAGE_PROJECTS',

  // SETTINGS
  SEE_SETTINGS: 'SEE_SETTINGS',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',

  // TEST CASE
  MANAGE_TEST_CASES: 'MANAGE_TEST_CASES',

  // TEST ITEM
  MANAGE_TEST_ITEMS: 'MANAGE_TEST_ITEMS',

  // TEST PLAN
  MANAGE_TEST_PLANS: 'MANAGE_TEST_PLANS',

  // USERS_MANAGEMENT
  MANAGE_USERS: 'MANAGE_USERS',

  ACCESS_INSTANCE_LEVEL_PAGES: 'ACCESS_INSTANCE_LEVEL_PAGES',
  ACTIVITY_OPTION: 'ACTIVITY_OPTION',
  EDIT_OWN_ACCOUNT: 'EDIT_OWN_ACCOUNT',
  INSTANCE_LEVEL_PLUGIN_PAGES: 'INSTANCE_LEVEL_PLUGIN_PAGES',
  MANAGE_BTS_ISSUES: 'MANAGE_BTS_ISSUES',
  READ_DATA: 'READ_DATA',
  RESIZE_AND_DRAG_WIDGETS: 'RESIZE_AND_DRAG_WIDGETS',
  SEE_DEMO_DATA: 'SEE_DEMO_DATA',
  SEE_EMAIL_MEMBERS: 'SEE_EMAIL_MEMBERS',
  SEE_MEMBERS: 'SEE_MEMBERS',
  SEE_ROW_ACTION_MENU: 'SEE_ROW_ACTION_MENU',
  VIEW_INFO_BILLING: 'VIEW_INFO_BILLING',
  WORK_WITH_DASHBOARD: 'WORK_WITH_DASHBOARD',
  WORK_WITH_DEFECT_TYPES: 'WORK_WITH_DEFECT_TYPES',
  WORK_WITH_FILTERS: 'WORK_WITH_FILTERS',
  WORK_WITH_TESTS: 'WORK_WITH_TESTS',
  WORK_WITH_WIDGETS: 'WORK_WITH_WIDGETS',
};

export const PERMISSIONS_MAP: PermissionsMap = {
  [MANAGER]: {
    [ACTIONS.SEE_SETTINGS]: true,
    [ACTIONS.UPDATE_SETTINGS]: true,
    [ACTIONS.MANAGE_USERS]: true,
    [ACTIONS.SEE_MEMBERS]: true,
    [ACTIONS.MANAGE_LAUNCHES]: true,
    [ACTIONS.MANAGE_TEST_ITEMS]: true,
    [ACTIONS.MANAGE_BTS_ISSUES]: true,
    [ACTIONS.WORK_WITH_FILTERS]: true,
    [ACTIONS.WORK_WITH_WIDGETS]: true,
    [ACTIONS.SEE_ORGANIZATION_MEMBERS]: true,
    [ACTIONS.MANAGE_ORGANIZATIONS]: true,
    [ACTIONS.MANAGE_PROJECTS]: true,
    [ACTIONS.VIEW_INFO_BILLING]: true,
    [ACTIONS.MANAGE_ORGANIZATIONS]: true,
    [ACTIONS.WORK_WITH_DEFECT_TYPES]: true,
    [ACTIONS.SEE_DEMO_DATA]: true,
    [ACTIONS.WORK_WITH_DASHBOARD]: true,
    [ACTIONS.WORK_WITH_TESTS]: true,
    [ACTIONS.SEE_EMAIL_MEMBERS]: true,
    [ACTIONS.SEE_ROW_ACTION_MENU]: true,
  },
  [MEMBER]: {
    [VIEWER]: {
      [ACTIONS.SEE_SETTINGS]: false,
      [ACTIONS.SEE_MEMBERS]: false,
    },
    [EDITOR]: {
      [ACTIONS.SEE_SETTINGS]: true,
      [ACTIONS.UPDATE_SETTINGS]: true,
      [ACTIONS.MANAGE_USERS]: true,
      [ACTIONS.SEE_MEMBERS]: true,
      [ACTIONS.MANAGE_LAUNCHES]: true,
      [ACTIONS.MANAGE_TEST_ITEMS]: true,
      [ACTIONS.MANAGE_BTS_ISSUES]: true,
      [ACTIONS.WORK_WITH_FILTERS]: true,
      [ACTIONS.WORK_WITH_WIDGETS]: true,
      [ACTIONS.MANAGE_PROJECTS]: true,
      [ACTIONS.WORK_WITH_DEFECT_TYPES]: true,
      [ACTIONS.SEE_DEMO_DATA]: true,
      [ACTIONS.WORK_WITH_DASHBOARD]: true,
      [ACTIONS.WORK_WITH_TESTS]: true,
      [ACTIONS.SEE_ROW_ACTION_MENU]: true,
      [ACTIONS.MANAGE_MANUAL_LAUNCHES]: true,
      [ACTIONS.MANAGE_TEST_CASES]: true,
      [ACTIONS.MANAGE_TEST_PLANS]: true,
    },
  },
};
