export const ALL_GROUP_TYPE = 'ALL';
export const NOTIFICATION_GROUP_TYPE = 'NOTIFICATION';
export const AUTHORIZATION_GROUP_TYPE = 'AUTH';
export const BTS_GROUP_TYPE = 'BTS';
export const ANALYZER_GROUP_TYPE = 'ANALYZER';
export const OTHER_GROUP_TYPE = 'OTHER';
