export const PERIOD_VALUES = {
  ONE_MONTH: '1M',
  THREE_MONTHS: '3M',
  SIX_MONTHS: '6M',
};

export const PERIOD_VALUES_LENGTH = {
  [PERIOD_VALUES.ONE_MONTH]: 30,
  [PERIOD_VALUES.THREE_MONTHS]: 12,
  [PERIOD_VALUES.SIX_MONTHS]: 24,
};
