export const projects = [
  {
    projectId: 1,
    projectName: 'superadmin_personal',
    usersQuantity: 27,
    launchesQuantity: 38,
    lastRun: 1552660028200,
    creationDate: 1552408580518,
    entryType: 'PERSONAL',
  },
  {
    projectId: 2,
    projectName: 'default_personal',
    usersQuantity: 8,
    launchesQuantity: 41,
    lastRun: 1552898486784,
    creationDate: 1552408580518,
    entryType: 'PERSONAL',
  },
  {
    projectId: 3,
    projectName: 'tester_personal',
    usersQuantity: 2,
    launchesQuantity: 0,
    creationDate: 1552446463656,
    entryType: 'PERSONAL',
  },
  {
    projectId: 4,
    projectName: 'testlongname_personal',
    usersQuantity: 2,
    launchesQuantity: 0,
    creationDate: 1552446680263,
    entryType: 'PERSONAL',
  },
  {
    projectId: 5,
    projectName: 'test35204_personal',
    usersQuantity: 1,
    launchesQuantity: 0,
    creationDate: 1552448358243,
    entryType: 'PERSONAL',
  },
  {
    projectId: 6,
    projectName: 'test352041_personal',
    usersQuantity: 2,
    launchesQuantity: 0,
    creationDate: 1552460831789,
    entryType: 'PERSONAL',
  },
  {
    projectId: 7,
    projectName: 'test352042_personal',
    usersQuantity: 1,
    launchesQuantity: 0,
    creationDate: 1552464339828,
    entryType: 'PERSONAL',
  },
  {
    projectId: 8,
    projectName: 'test352043_personal',
    usersQuantity: 1,
    launchesQuantity: 0,
    creationDate: 1552464381924,
    entryType: 'PERSONAL',
  },
  {
    projectId: 9,
    projectName: 'qqqqqq_personal',
    usersQuantity: 1,
    launchesQuantity: 0,
    creationDate: 1552487702085,
    entryType: 'PERSONAL',
  },
  {
    projectId: 10,
    projectName: 'admin_personal',
    usersQuantity: 1,
    launchesQuantity: 0,
    creationDate: 1552548858268,
    entryType: 'PERSONAL',
  },
  {
    projectId: 11,
    projectName: 'admin_personal_1',
    usersQuantity: 2,
    launchesQuantity: 0,
    creationDate: 1552549459960,
    entryType: 'PERSONAL',
  },
  {
    projectId: 13,
    projectName: 'member1552574895251_personal',
    usersQuantity: 1,
    launchesQuantity: 0,
    creationDate: 1552574895540,
    entryType: 'PERSONAL',
  },
];

export const state = {
  user: {
    info: {
      id: 1,
      userId: 'superadmin',
      email: 'superadminemail@domain.com',
      photoId: 'L2RhdGEvc3RvcmFnZS9zdXBlcmFkbWlu',
      fullName: 'tester',
      accountType: 'INTERNAL',
      userRole: 'ADMINISTRATOR',
      photoLoaded: true,
      metadata: {
        last_login: 1552559284869,
      },
      assignedProjects: {
        admin_personal: {
          projectRole: 'PROJECT_MANAGER',
          entryType: 'PERSONAL',
        },
        testlongname_personal: {
          projectRole: 'PROJECT_MANAGER',
          entryType: 'PERSONAL',
        },
        tester_personal: {
          projectRole: 'PROJECT_MANAGER',
          entryType: 'PERSONAL',
        },
        superadmin_personal: {
          projectRole: 'PROJECT_MANAGER',
          entryType: 'PERSONAL',
        },
        admin_personal_1: {
          projectRole: 'PROJECT_MANAGER',
          entryType: 'PERSONAL',
        },
        test352041_personal: {
          projectRole: 'PROJECT_MANAGER',
          entryType: 'PERSONAL',
        },
      },
    },
    activeProject: 'superadmin_personal',
    settings: {
      startTimeFormat: 'relative',
      photoTimeStamp: 1552561241887,
    },
    token: '09b8b872-64fb-42fb-8906-32ff23af1eea',
  },
};
