export const ALL = 'ALL';
export const OWNER = 'OWNER';
export const PERMISSION_ROLES = ['ADMIN', 'MANAGER', 'MEMBER', 'OPERATOR', 'CUSTOMER'];
export const PERMISSIONS_MAP = {
  ADMIN: {
    accessToManagementSystem: ALL,
    createProject: ALL,
    deleteProject: ALL,
    updateSettings: ALL,
    seeSettings: ALL,
    createInternalUser: ALL,
    inviteInternalUser: ALL,
    unSlashAssignInternalUser: ALL,
    changeUserRole: ALL,
    delUser: ALL,
    seeMembers: ALL,
    editOwnAccount1: ALL,
    deleteLaunch: ALL,
    forceFinishLaunch: ALL,
    startAnalysis: ALL,
    deleteTestItem: ALL,
    moveToDebug: ALL,
    mergeLaunches: ALL,
    workWithFiltersEtc: ALL,
    readData: ALL,
  },
  MANAGER: {
    updateSettings: ALL,
    seeSettings: ALL,
    inviteInternalUser: ALL,
    unSlashAssignInternalUser: ALL,
    changeUserRole: ALL,
    seeMembers: ALL,
    editOwnAccount1: ALL,
    deleteLaunch: ALL,
    forceFinishLaunch: ALL,
    startAnalysis: ALL,
    deleteTestItem: ALL,
    moveToDebug: ALL,
    mergeLaunches: ALL,
    workWithFiltersEtc: ALL,
    readData: ALL,
  },
  MEMBER: {
    seeSettings: ALL,
    seeMembers: ALL,
    editOwnAccount1: ALL,
    deleteLaunch: OWNER,
    forceFinishLaunch: OWNER,
    startAnalysis: ALL,
    deleteTestItem: OWNER,
    moveToDebug: OWNER,
    mergeLaunches: OWNER,
    workWithFiltersEtc: ALL,
    readData: ALL,
  },
  OPERATOR: {
    seeSettings: ALL,
    seeMembers: ALL,
    editOwnAccount1: ALL,
    startAnalysis: ALL,
    workWithFiltersEtc: ALL,
    readData: ALL,
  },
  CUSTOMER: {
    seeSettings: ALL,
    editOwnAccount1: ALL,
    deleteLaunch: OWNER,
    forceFinishLaunch: OWNER,
    startAnalysis: ALL,
    deleteTestItem: OWNER,
    mergeLaunches: OWNER,
    workWithFiltersEtc: ALL,
    readData: ALL,
  },
};
