export const PermissionsConfig = {
  accessToManagementSystem: {
    permissions: {
      admin: true,
      manager: false,
      memberOwner: false,
      memberNotOwner: false,
      operator: false,
      customerOwner: false,
      customerNotOwner: false,
    },
  },
  createProject: {
    permissions: {
      admin: true,
      manager: false,
      memberOwner: false,
      memberNotOwner: false,
      operator: false,
      customerOwner: false,
      customerNotOwner: false,
    },
  },
  deleteProject: {
    permissions: {
      admin: true,
      manager: false,
      memberOwner: false,
      memberNotOwner: false,
      operator: false,
      customerOwner: false,
      customerNotOwner: false,
    },
  },
  updateSettings: {
    permissions: {
      admin: true,
      manager: true,
      memberOwner: false,
      memberNotOwner: false,
      operator: false,
      customerOwner: false,
      customerNotOwner: false,
    },
  },
  seeSettings: {
    permissions: {
      admin: true,
      manager: true,
      memberOwner: true,
      memberNotOwner: true,
      operator: true,
      customerOwner: true,
      customerNotOwner: true,
    },
  },
  createInternalUser: {
    permissions: {
      admin: true,
      manager: false,
      memberOwner: false,
      memberNotOwner: false,
      operator: false,
      customerOwner: false,
      customerNotOwner: false,
    },
  },
  inviteInternalUser: {
    permissions: {
      admin: true,
      manager: true,
      memberOwner: false,
      memberNotOwner: false,
      operator: false,
      customerOwner: false,
      customerNotOwner: false,
    },
  },
  unSlashAssignInternalUser: {
    permissions: {
      admin: true,
      manager: true,
      memberOwner: false,
      memberNotOwner: false,
      operator: false,
      customerOwner: false,
      customerNotOwner: false,
    },
  },
  changeUserRole: {
    permissions: {
      admin: true,
      manager: true,
      memberOwner: false,
      memberNotOwner: false,
      operator: false,
      customerOwner: false,
      customerNotOwner: false,
    },
  },
  delUser: {
    permissions: {
      admin: true,
      manager: false,
      memberOwner: false,
      memberNotOwner: false,
      operator: false,
      customerOwner: false,
      customerNotOwner: false,
    },
  },
  seeMembers: {
    permissions: {
      admin: true,
      manager: true,
      memberOwner: true,
      memberNotOwner: true,
      operator: true,
      customerOwner: false,
      customerNotOwner: false,
    },
  },
  editOwnAccount1: {
    permissions: {
      admin: true,
      manager: true,
      memberOwner: true,
      memberNotOwner: true,
      operator: true,
      customerOwner: true,
      customerNotOwner: true,
    },
    attention: true,
  },
  deleteLaunch: {
    permissions: {
      admin: true,
      manager: true,
      memberOwner: true,
      memberNotOwner: false,
      operator: false,
      customerOwner: true,
      customerNotOwner: false,
    },
  },
  forceFinishLaunch: {
    permissions: {
      admin: true,
      manager: true,
      memberOwner: true,
      memberNotOwner: false,
      operator: true,
      customerOwner: true,
      customerNotOwner: false,
    },
  },
  startAnalysis: {
    permissions: {
      admin: true,
      manager: true,
      memberOwner: true,
      memberNotOwner: true,
      operator: true,
      customerOwner: true,
      customerNotOwner: true,
    },
  },
  deleteTestItem: {
    permissions: {
      admin: true,
      manager: true,
      memberOwner: true,
      memberNotOwner: false,
      operator: false,
      customerOwner: true,
      customerNotOwner: false,
    },
  },
  moveToDebug: {
    permissions: {
      admin: true,
      manager: true,
      memberOwner: true,
      memberNotOwner: false,
      operator: false,
      customerOwner: false,
      customerNotOwner: false,
    },
  },
  mergeLaunches: {
    permissions: {
      admin: true,
      manager: true,
      memberOwner: true,
      memberNotOwner: false,
      operator: true,
      customerOwner: true,
      customerNotOwner: false,
    },
  },
  workWithFiltersEtc: {
    permissions: {
      admin: true,
      manager: true,
      memberOwner: true,
      memberNotOwner: true,
      operator: true,
      customerOwner: true,
      customerNotOwner: true,
    },
  },
  readData: {
    permissions: {
      admin: true,
      manager: true,
      memberOwner: true,
      memberNotOwner: true,
      operator: true,
      customerOwner: true,
      customerNotOwner: true,
    },
  },
};
