/*
 * Copyright 2022 EPAM Systems
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { defineMessages } from 'react-intl';

export const messages = defineMessages({
  tabDescription: {
    id: 'IndexSettings.tabDescription',
    defaultMessage:
      'Each log entry along with its defect type is automatically saved to the search engine in the form of a separate document. All documents created compose an Index. The more test results index has, the more accurate results will be generated by the end of the analysis process. More information about Index Settings you can read in <a>Documentation</a>',
  },
  regenerateIndexDescription: {
    id: 'IndexSettings.regenerateIndexDescription',
    defaultMessage:
      'You have changed a parameter "Number of log lines". This action can influence on results of an analysis. For an appropriate work of the analyzer, please regenerate Index in the search engine. Do you want to regenerate it now?',
  },
  inCaseOf: {
    id: 'IndexSettings.inCaseOf',
    defaultMessage: 'In case of',
  },
  removeIndexDescription: {
    id: 'IndexSettings.removeIndexDescription',
    defaultMessage:
      'all data with your investigations will be deleted from the search engine. To add new data you could generate index or investigate test results manually.',
  },
  generateIndexDescription: {
    id: 'IndexSettings.generateIndexDescription',
    defaultMessage:
      'all data is removed from the search engine and new one is generated based on all previous investigations on the project. You can start using auto-analysis after receiving an e-mail about the end of the generation process.',
  },
  indexActionsBlockTitle: {
    id: 'IndexSettings.title',
    defaultMessage: 'Actions with index',
  },
  generateIndexButtonCaption: {
    id: 'IndexSettings.generateIndexButtonCaption',
    defaultMessage: 'Generate Index',
  },
  regenerateIndexTitle: {
    id: 'IndexSettings.regenerateIndexTitle',
    defaultMessage: 'Regenerate index',
  },
  removeIndexButtonCaption: {
    id: 'IndexSettings.removeIndexButtonCaption',
    defaultMessage: 'Remove Index',
  },
  regenerateIndexProgress: {
    id: 'IndexSettings.regenerateIndexProgress',
    defaultMessage: 'Please wait, we generate new index',
  },
});
