/*
 * Copyright 2025 EPAM Systems
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { FilterOption } from './types';
import { IScenario, TestCase } from '../types';

export const mockTestCases: TestCase[] = [
  {
    id: 'a3f1e2b4-6c7d-4e8a-9f3b-2c1d3e4f5a6b',
    name: 'User Authentication Scenario Alpha',
    priority: 'high',
    path: ['Order history', 'Data migration', 'Email notifications', 'Cart management'],
    tags: [
      'sso system',
      'user interface improvements',
      'battery usage analysis for a',
      'cross-platform app speed t',
      'ui',
      'performance test',
      'security check',
      'user flow',
      'ui',
      'performance test',
      'security check',
      'user flow',
      'ui',
      'performance test',
      'security check',
      'user flow',
      'ui',
      'performance test',
      'security check',
      'user flow',
      'ui',
      'performance test',
      'security check',
    ],
    created: 1711284904218,
    lastExecution: 1711198504218,
    durationTime: 960000,
  },
  {
    id: 'b4e2f3c5-7d8e-5f9a-af4c-3d2e4f5a6b7c',
    name: 'Login Functionality Check Beta',
    priority: 'medium',
    path: ['User Management', 'Authentication', 'Login'],
    tags: [],
    created: 1711198504218,
    lastExecution: 1711371304218,
    durationTime: 1800000,
  },
  {
    id: 'c5f3a4b6-8e9f-6a0b-ba5d-4e3f5a6b7c8d',
    name: 'Account Access Verification Delta',
    priority: 'low',
    path: ['Security', 'Account Verification'],
    tags: [
      'sso system',
      'user interface improvements',
      'battery usage analysis for a',
      'cross-platform app speed t',
      'ui',
    ],
    created: 1711112104218,
    lastExecution: 1711112104218,
    durationTime: 600000,
  },
  {
    id: 'd6a4b5c7-9fae-7b1c-cb6e-5f4a6b7c8d9e',
    name: 'User Sign-In Validation Process for Gamma Systems',
    priority: 'blocker',
    path: ['Authentication', 'Validation', 'User Sign-In'],
    tags: [],
    created: 1708693704218,
    lastExecution: 1708693704218,
    durationTime: 2400000,
  },
  {
    id: 'e7b5c6d8-afbf-8c2d-dc7f-6a5b7c8d9eaf',
    name: 'Credential Submission Assessment Epsilon',
    priority: 'critical',
    path: ['Security', 'Credentials', 'Submission'],
    tags: [
      'ai bug',
      'performance test',
      'security check',
      'user flow',
      'api validation',
      'data integrity',
      'cross-browser',
      'accessibility',
      'regression',
      'smoke test',
      'load test',
      'integration',
      'end-to-end',
      'user acceptance',
      'functionality',
    ],
    created: 1710847304218,
    lastExecution: 1710847304218,
    durationTime: 3600000,
  },
  {
    id: 'f8c6d7e9-bacf-9d3e-ed8a-7b6c8d9eafba',
    name: 'Login Process Evaluation Zeta',
    priority: 'unspecified',
    path: ['Authentication', 'Login Process'],
    tags: [
      'sso system',
      'user interface improvements',
      'battery usage analysis for a',
      'cross-platform app speed t',
      'ui',
    ],
    created: 1711025704218,
    lastExecution: 1711371304218,
    durationTime: 1200000,
  },
  {
    id: 'a9d7e8f0-cdef-8e4f-fe9b-8c7d9eafbacb',
    name: 'User Entry Confirmation Eta',
    priority: 'medium',
    path: ['User Management', 'Entry Confirmation'],
    tags: [
      'sso system',
      'user interface improvements',
      'battery usage analysis for speed',
      'cross-platform app speed t',
      'ui',
    ],
    created: 1710939304218,
    lastExecution: 1711198504218,
    durationTime: 900000,
  },
  {
    id: 'bae8f9a1-defa-9f5a-afac-9d8eafbacbcd',
    name: 'Dashboard Navigation Flow Test',
    priority: 'low',
    path: ['UI', 'Dashboard', 'Navigation'],
    tags: ['navigation', 'ui', 'dashboard', 'user flow'],
    created: 1711371304218,
    lastExecution: 1711457704218,
    durationTime: 480000,
  },
  {
    id: 'cbfa0b2c-efab-a06b-bfcd-ae9fbacbcdde',
    name: 'Data Export Functionality Verification',
    priority: 'high',
    path: ['Data Management', 'Export', 'Functionality'],
    tags: ['export', 'data processing', 'file handling', 'performance'],
    created: 1710675304218,
    lastExecution: 1710675304218,
    durationTime: 1800000,
  },
  {
    id: 'dcab1c3d-fabc-b17c-caed-bfafbacbcdde',
    name: 'Mobile Responsive Design Check',
    priority: 'medium',
    path: ['UI', 'Mobile', 'Responsive Design'],
    tags: ['mobile', 'responsive', 'css', 'media queries', 'cross-device'],
    created: 1711414504218,
    lastExecution: 1711414504218,
    durationTime: 720000,
  },
  {
    id: 'edbc2d4e-abcd-c28d-dbfe-cfbacbcddefe',
    name: 'API Integration Security Test',
    priority: 'high',
    path: ['API', 'Integration', 'Security'],
    tags: ['api', 'security', 'authentication', 'authorization', 'oauth'],
    created: 1710674504218,
    lastExecution: 1710674504218,
    durationTime: 2100000,
  },
  {
    id: 'fecd3e5f-bcde-d39e-ecaf-dfbcbcddefefa',
    name: 'Database Connection Stability',
    priority: 'high',
    path: ['Database', 'Connection', 'Stability'],
    tags: ['database', 'connection', 'stability', 'performance'],
    created: 1711455904218,
    lastExecution: 1711455904218,
    durationTime: 600000,
  },
  {
    id: 'afde4f6a-cdef-e4af-fdba-efcbcddefeab',
    name: 'Payment Gateway Integration',
    priority: 'high',
    path: ['Payment', 'Gateway', 'Integration'],
    tags: ['payment', 'gateway', 'integration', 'transaction', 'security'],
    created: 1711450304218,
    lastExecution: 1711450304218,
    durationTime: 1500000,
  },
  {
    id: 'baef5a7b-defa-f5ba-aecb-fabcddefefabc',
    name: 'Email Notification System',
    priority: 'medium',
    path: ['Communication', 'Email', 'Notifications'],
    tags: ['email', 'notification', 'smtp', 'template'],
    created: 1711436704218,
    lastExecution: 1711436704218,
    durationTime: 840000,
  },
  {
    id: 'cbfa6b8c-efab-a6cb-bfdc-abcddefabcde',
    name: 'File Upload Size Validation',
    priority: 'low',
    path: ['File Management', 'Upload', 'Validation'],
    tags: ['file upload', 'validation', 'size limit', 'error handling'],
    created: 1711371304218,
    lastExecution: 1711371304218,
    durationTime: 300000,
  },
  {
    id: 'dcab7c9d-fabc-b7dc-caed-bcdefabcdefa',
    name: 'Search Filter Performance',
    priority: 'medium',
    path: ['Search', 'Filter', 'Performance'],
    tags: ['search', 'filter', 'performance', 'optimization', 'indexing'],
    created: 1711447504218,
    lastExecution: 1711447504218,
    durationTime: 960000,
  },
  {
    id: 'edac8d0e-abcd-c8ed-dbfe-cdefabcdefab',
    name: 'User Profile Update Workflow',
    priority: 'low',
    path: ['User Management', 'Profile', 'Update'],
    tags: ['profile', 'update', 'user management', 'validation'],
    created: 1711429504218,
    lastExecution: 1711429504218,
    durationTime: 420000,
  },
  {
    id: 'febd9e1f-bcde-d9fe-ecaf-defabcdefabc',
    name: 'Multi-language Support Test',
    priority: 'low',
    path: ['Localization', 'Multi-language', 'Support'],
    tags: ['i18n', 'localization', 'language', 'translation'],
    created: 1709675504218,
    lastExecution: 1709675504218,
    durationTime: 1200000,
  },
  {
    id: 'afce0f2a-cdef-e0af-fdba-efabcdefabcd',
    name: 'Shopping Cart Persistence',
    priority: 'medium',
    path: ['E-commerce', 'Shopping Cart', 'Persistence'],
    tags: ['shopping cart', 'persistence', 'session', 'local storage'],
    created: 1711454604218,
    lastExecution: 1711454604218,
    durationTime: 540000,
  },
  {
    id: 'badf1a3b-defa-f1ba-aecb-fabcdefabcde',
    name: 'Social Media Login Integration',
    priority: 'medium',
    path: ['Authentication', 'Social Media', 'Login'],
    tags: ['social login', 'oauth', 'facebook', 'google', 'integration'],
    created: 1711443904218,
    lastExecution: 1711443904218,
    durationTime: 780000,
  },
  {
    id: 'cbea2b4c-efab-a2cb-bfdc-abcdefabcdef',
    name: 'Report Generation Performance',
    priority: 'medium',
    path: ['Reports', 'Generation', 'Performance'],
    tags: ['reports', 'generation', 'performance', 'pdf', 'excel'],
    created: 1711371304218,
    lastExecution: 1711371304218,
    durationTime: 1800000,
  },
  {
    id: 'dcfb3c5d-fabc-b3dc-caed-bcdefabcdefab',
    name: 'Real-time Chat Functionality',
    priority: 'high',
    path: ['Communication', 'Chat', 'Real-time'],
    tags: ['chat', 'real-time', 'websocket', 'messaging'],
    created: 1711450304218,
    lastExecution: 1711450304218,
    durationTime: 900000,
  },
  {
    id: 'edac4d6e-abcd-c4ed-dbfe-cdefabcdefabc',
    name: 'Backup System Reliability',
    priority: 'high',
    path: ['System', 'Backup', 'Reliability'],
    tags: ['backup', 'reliability', 'data recovery', 'system'],
    created: 1711414504218,
    lastExecution: 1711414504218,
    durationTime: 1200000,
  },
  {
    id: 'febd5e7f-bcde-d5fe-ecaf-defabcdefabcd',
    name: 'Browser Compatibility Check',
    priority: 'low',
    path: ['Testing', 'Browser', 'Compatibility'],
    tags: ['browser', 'compatibility', 'cross-browser', 'testing'],
    created: 1711198504218,
    lastExecution: 1711198504218,
    durationTime: 600000,
  },
  {
    id: 'afce6f8a-cdef-e6af-fdba-efabcdefabcde',
    name: 'Load Balancer Configuration',
    priority: 'high',
    path: ['Infrastructure', 'Load Balancer', 'Configuration'],
    tags: ['load balancer', 'configuration', 'scaling', 'performance'],
    created: 1711457704218,
    lastExecution: 1711457704218,
    durationTime: 720000,
  },
  {
    id: 'badf7a9b-defa-f7ba-aecb-fabcdefabcdef',
    name: 'User Session Management',
    priority: 'medium',
    path: ['User Management', 'Session', 'Management'],
    tags: ['session', 'management', 'timeout', 'security'],
    created: 1711439504218,
    lastExecution: 1711439504218,
    durationTime: 660000,
  },
  {
    id: 'cbea8bac-efab-a8cb-bfdc-abcdefabcdefab',
    name: 'Content Management System',
    priority: 'medium',
    path: ['CMS', 'Content', 'Management'],
    tags: ['cms', 'content', 'management', 'editor', 'publishing'],
    created: 1711432304218,
    lastExecution: 1711432304218,
    durationTime: 1080000,
  },
  {
    id: 'dcfb9cbd-fabc-b9dc-caed-bcdefabcdefabc',
    name: 'Image Processing Pipeline',
    priority: 'low',
    path: ['Media', 'Image Processing', 'Pipeline'],
    tags: ['image', 'processing', 'pipeline', 'optimization', 'resize'],
    created: 1711425104218,
    lastExecution: 1711425104218,
    durationTime: 1500000,
  },
  {
    id: 'edacacde-abcd-cace-dbfe-cdefabcdefabcd',
    name: 'Third-party API Rate Limiting',
    priority: 'medium',
    path: ['API', 'Third-party', 'Rate Limiting'],
    tags: ['api', 'rate limiting', 'third-party', 'throttling'],
    created: 1710674504218,
    lastExecution: 1710674504218,
    durationTime: 960000,
  },
  {
    id: 'feadbdef-bcde-dbfe-ecaf-defabcdefabcde',
    name: 'Data Synchronization Process',
    priority: 'high',
    path: ['Data Management', 'Synchronization', 'Process'],
    tags: ['data sync', 'synchronization', 'consistency', 'replication'],
    created: 1711456704218,
    lastExecution: 1711456704218,
    durationTime: 1800000,
  },
  {
    id: 'afbecefa-cdef-ecaf-fdba-efabcdefabcdef',
    name: 'Security Vulnerability Scan',
    priority: 'high',
    path: ['Security', 'Vulnerability', 'Scan'],
    tags: ['security', 'vulnerability', 'scan', 'penetration testing'],
    created: 1711198504218,
    lastExecution: 1711198504218,
    durationTime: 2400000,
  },
  {
    id: 'bacfdfab-defa-fdba-aecb-fabcdefabcdefab',
    name: 'Microservices Communication',
    priority: 'medium',
    path: ['Architecture', 'Microservices', 'Communication'],
    tags: ['microservices', 'communication', 'service mesh', 'api gateway'],
    created: 1711447504218,
    lastExecution: 1711447504218,
    durationTime: 720000,
  },
  {
    id: 'cbdaeabc-efab-eacb-bfdc-abcdefabcdefabc',
    name: 'Caching Strategy Implementation',
    priority: 'low',
    path: ['Performance', 'Caching', 'Strategy'],
    tags: ['caching', 'strategy', 'redis', 'performance', 'optimization'],
    created: 1711436704218,
    lastExecution: 1711436704218,
    durationTime: 900000,
  },
  {
    id: 'dcebfbcd-fabc-fbdc-caed-bcdefabcdefabcd',
    name: 'Machine Learning Model Deployment',
    priority: 'high',
    path: ['AI', 'Machine Learning', 'Deployment'],
    tags: ['ml', 'model', 'deployment', 'ai', 'prediction'],
    created: 1711457104218,
    lastExecution: 1711457104218,
    durationTime: 3600000,
  },
  {
    id: 'edfcacde-abcd-fcac-dbfe-cdefabcdefabcde',
    name: 'Kubernetes Cluster Health Check',
    priority: 'high',
    path: ['DevOps', 'Kubernetes', 'Health Check'],
    tags: ['kubernetes', 'cluster', 'health', 'monitoring', 'devops'],
    created: 1711457704218,
    lastExecution: 1711457704218,
    durationTime: 600000,
  },
];

export const STATUS_TYPES = {
  BLOCKER: 'blocker',
  CRITICAL: 'critical',
  HIGH: 'high',
  MEDIUM: 'medium',
  LOW: 'low',
  UNSPECIFIED: 'unspecified',
} as const;

export const ITEMS_PER_PAGE_OPTIONS: number[] = [10, 25, 50, 100];

export const FILTER_OPTIONS: FilterOption[] = [
  { label: 'All Priorities', value: 'all' },
  { label: 'Blocker', value: STATUS_TYPES.BLOCKER },
  { label: 'Critical', value: STATUS_TYPES.CRITICAL },
  { label: 'High Priority', value: STATUS_TYPES.HIGH },
  { label: 'Medium Priority', value: STATUS_TYPES.MEDIUM },
  { label: 'Low Priority', value: STATUS_TYPES.LOW },
  { label: 'Unspecified', value: STATUS_TYPES.UNSPECIFIED },
];

export const mockedTestCaseDescription =
  'Ideally you should have a test method for each separate unit of work so you can always immediately view where things are going wrong. In this example there is a basic method called getUserById() which will return a user and there is a total of 3 unit of works. Ideally you should have a test method for each separate unit of work so you can always immediately view where things are going wrong. In this example there is a basic method called getUserById() which will return a user and there is a total of 3 unit of works';

export const mockedScenarios: IScenario[] = [
  {
    id: '1',
    precondition:
      'Ideally you should have a test method for each separate unit of work so you can always immediately view where things are going wrong. In this example there is a basic method called getUserById() which will return a user and there is a total of 3 unit of works',
    instruction: '',
    expectedResult: '',
    attachments: [],
  },
  {
    id: '2',
    precondition:
      'Ideally you should have a test method for each separate unit of work so you can always immediately view where things are going wrong. In this example there is a basic method called getUserById() which will return a user and there is a total of 3 unit of works',
    instruction: '',
    expectedResult: '',
    attachments: [
      { fileName: 'Slack_plugin.jar', size: 128 },
      { fileName: 'RALLY_plugin.jar', size: 62 },
      { fileName: 'Screenshot 2023-09-08 at 16.23.58.png', size: 0.6 },
      { fileName: 'Jira_plugin.jar', size: 12 },
    ],
  },
  {
    id: '3',
    precondition:
      'Ideally you should have a test method for each separate unit of work so you can always immediately view where things are going wrong. In this example there is a basic method called getUserById() which will return a user and there is a total of 3 unit of works',
    instruction:
      'Ideally you should have a test method for each separate unit of work so you can always immediately view where things are going wrong. In this example there is a basic method called getUserById() which will return a user and there is a total of 3 unit of works an always immediately view where things are going wrong. In this example there is a basic method called',
    expectedResult:
      'Example there is a basic method called getUserById() which will return a user and there is a total of 3 unit of works',
    attachments: [],
  },
];
