export const GENERATE_DEMO_DATA = 'GENERATE_DEMO_DATA';
export const GENERATE_DEMO_DATA_SUCCESS = 'GENERATE_DEMO_DATA_SUCCESS';
export const GENERATE_DEMO_DATA_FAILURE = 'GENERATE_DEMO_DATA_FAILURE';

